version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=your_password
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=your_password
  ruumi-back:
    build: .
    ports:
      - "8000:8000"
    links:
      - mongo:db_host
    environment:
      AUTH: your_auth_key
      DB_HOST: db_host
    depends_on:
      - mongo